pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Initialize NuGet tooling'
  
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Run unit tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    #testAssemblyVer2: '$(Build.SourcesDirectory)\Gear.ActiveExpressions.Tests\bin\Release\Gear.ActiveExpressions.Tests.dll'
    codeCoverageEnabled: true

- task: CopyFiles@2
  displayName: 'Copy artifacts to staging'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**\$(BuildConfiguration)\**\?(*.nupkg)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop