pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Initialize NuGet tooling'
  
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Execute and collect code coverage of unit tests (NETFramework)'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: true

- task: DotNetCoreCLI@2
  displayName: 'Execute and collect code coverage of unit tests (NETCore)'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: CopyFiles@2
  displayName: 'Copy artifacts to staging'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**\$(buildConfiguration)\**\?(*.nupkg)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop