pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Initialize NETCore 3.0 runtime'
  inputs:
    packageType: 'runtime'
    version: '3.0.0-preview3-27503-5' 

- task: DotNetCoreInstaller@0
  displayName: 'Initialize NETCore 3.0 tooling'
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview3-010431' 

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Execute and collect code coverage of unit tests'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGets'
  inputs:
    command: 'pack'
    projects: '**/*!(*Test*)/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy artifacts to staging'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/$(buildConfiguration)/**/?(*.nupkg)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop